// pages/account/payment.vue
<template>
  <div class="min-h-screen flex flex-col bg-gray-50">
    <AppNavbar />

    <main class="flex-1 py-8">
      <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

        <!-- Header -->
        <NuxtLink to="/account">
          <button class="flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-6 transition-colors">
            <ArrowLeft class="h-4 w-4" /> Back to Dashboard
          </button>
        </NuxtLink>

        <div class="mb-8">
          <h1 class="text-3xl font-bold text-gray-900">Payment Methods</h1>
          <p class="text-gray-500 mt-1">Manage how you pay for your Fortress Designs orders.</p>
        </div>

        <!-- Polar.sh Demo Banner -->
        <div class="bg-gradient-to-r from-blue-600 to-violet-600 rounded-2xl p-5 mb-8 flex items-start gap-4">
          <div class="w-10 h-10 rounded-xl bg-white/20 flex items-center justify-center shrink-0 mt-0.5">
            <Zap class="h-5 w-5 text-white" />
          </div>
          <div>
            <p class="text-white font-semibold mb-0.5">Powered by Polar.sh</p>
            <p class="text-blue-100 text-sm leading-relaxed">Secure, fast, and modern payments. Full Polar.sh integration coming soon — payment keys pending setup.</p>
            <span class="inline-flex items-center gap-1.5 mt-2 text-xs font-semibold bg-white/20 text-white px-3 py-1 rounded-full">
              <Clock class="h-3 w-3" /> Demo Mode Active
            </span>
          </div>
        </div>

        <!-- Saved Cards -->
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 mb-6">
          <div class="p-6 border-b border-gray-100 flex items-center justify-between">
            <div class="flex items-center gap-3">
              <CreditCard class="h-5 w-5 text-primary" />
              <h2 class="text-lg font-semibold text-gray-900">Saved Cards</h2>
            </div>
            <button
              @click="showAddCard = !showAddCard"
              class="flex items-center gap-2 text-sm font-medium text-primary hover:text-purple-700 border border-primary hover:bg-primary hover:text-white px-3 py-1.5 rounded-lg transition-colors"
            >
              <Plus class="h-4 w-4" /> Add Card
            </button>
          </div>

          <!-- Demo Cards -->
          <div class="p-6 space-y-4">
            <div
              v-for="card in demoCards"
              :key="card.id"
              class="flex items-center justify-between p-4 rounded-xl border transition-all duration-200 cursor-pointer"
              :class="selectedCard === card.id ? 'border-primary bg-purple-50 ring-1 ring-primary' : 'border-gray-100 hover:border-gray-200 hover:bg-gray-50'"
              @click="selectedCard = card.id"
            >
              <div class="flex items-center gap-4">
                <!-- Card brand icon -->
                <div class="w-12 h-8 rounded-lg flex items-center justify-center text-white text-xs font-bold shrink-0"
                  :class="card.brand === 'Visa' ? 'bg-blue-600' : card.brand === 'Mastercard' ? 'bg-red-500' : 'bg-gray-800'">
                  {{ card.brand === 'Amex' ? 'AMEX' : card.brand.toUpperCase() }}
                </div>
                <div>
                  <p class="font-medium text-gray-900 text-sm">{{ card.brand }} ending in {{ card.last4 }}</p>
                  <p class="text-xs text-gray-500">Expires {{ card.expiry }} · {{ card.holder }}</p>
                </div>
              </div>
              <div class="flex items-center gap-3">
                <span v-if="card.isDefault" class="text-xs font-medium text-primary bg-purple-100 px-2 py-0.5 rounded-full">Default</span>
                <div
                  class="w-5 h-5 rounded-full border-2 flex items-center justify-center"
                  :class="selectedCard === card.id ? 'border-primary bg-primary' : 'border-gray-300'"
                >
                  <div v-if="selectedCard === card.id" class="w-2 h-2 rounded-full bg-white" />
                </div>
              </div>
            </div>

            <!-- Add Card Form (demo) -->
            <div v-if="showAddCard" class="border border-dashed border-gray-300 rounded-xl p-5 space-y-4">
              <p class="text-sm font-medium text-gray-700 flex items-center gap-2">
                <Lock class="h-4 w-4 text-green-500" /> Secure Card Entry
                <span class="ml-auto text-xs text-gray-400 font-normal flex items-center gap-1">
                  <span class="w-2 h-2 rounded-full bg-amber-400 inline-block"></span> Demo Mode
                </span>
              </p>
              <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Cardholder Name</label>
                <input v-model="newCard.holder" type="text" placeholder="John Doe" class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary text-sm" />
              </div>
              <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Card Number</label>
                <div class="relative">
                  <input v-model="newCard.number" type="text" placeholder="4242 4242 4242 4242" maxlength="19" class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary text-sm pr-12" @input="formatCardNumber" />
                  <CreditCard class="absolute right-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400" />
                </div>
              </div>
              <div class="grid grid-cols-2 gap-4">
                <div>
                  <label class="block text-xs font-medium text-gray-600 mb-1">Expiry (MM/YY)</label>
                  <input v-model="newCard.expiry" type="text" placeholder="12/27" maxlength="5" class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary text-sm" />
                </div>
                <div>
                  <label class="block text-xs font-medium text-gray-600 mb-1">CVC</label>
                  <input v-model="newCard.cvc" type="password" placeholder="•••" maxlength="4" class="w-full px-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary text-sm" />
                </div>
              </div>
              <div class="p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-700 flex items-start gap-2">
                <AlertCircle class="h-4 w-4 shrink-0 mt-0.5" />
                <span>This is a demo — no real card data is stored or transmitted. Full Polar.sh payment processing will be enabled once API keys are configured.</span>
              </div>
              <div class="flex gap-3">
                <button @click="showAddCard = false" class="flex-1 border border-gray-300 text-gray-600 hover:bg-gray-50 px-4 py-2.5 rounded-xl text-sm font-medium transition-colors">Cancel</button>
                <button @click="addDemoCard" class="flex-1 bg-primary hover:bg-purple-700 text-white px-4 py-2.5 rounded-xl text-sm font-medium transition-colors flex items-center justify-center gap-2">
                  <Plus class="h-4 w-4" /> Save Card
                </button>
              </div>
            </div>
          </div>
        </div>

        <!-- Polar.sh Wallet (demo) -->
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 mb-6">
          <div class="p-6 border-b border-gray-100 flex items-center gap-3">
            <Wallet class="h-5 w-5 text-primary" />
            <h2 class="text-lg font-semibold text-gray-900">Digital Wallets</h2>
          </div>
          <div class="p-6 space-y-3">
            <div v-for="wallet in wallets" :key="wallet.id"
              class="flex items-center justify-between p-4 rounded-xl border border-gray-100 hover:border-gray-200 hover:bg-gray-50 transition-all">
              <div class="flex items-center gap-3">
                <div class="w-10 h-10 rounded-xl flex items-center justify-center" :class="wallet.color">
                  <component :is="wallet.icon" class="h-5 w-5" />
                </div>
                <div>
                  <p class="font-medium text-gray-900 text-sm">{{ wallet.name }}</p>
                  <p class="text-xs text-gray-500">{{ wallet.description }}</p>
                </div>
              </div>
              <span class="text-xs font-medium text-amber-600 bg-amber-50 border border-amber-200 px-2.5 py-1 rounded-full">Coming Soon</span>
            </div>
          </div>
        </div>

        <!-- Billing Info -->
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100">
          <div class="p-6 border-b border-gray-100 flex items-center gap-3">
            <Receipt class="h-5 w-5 text-primary" />
            <h2 class="text-lg font-semibold text-gray-900">Billing Address</h2>
          </div>
          <div class="p-6">
            <p class="text-sm text-gray-500 mb-4">Your billing address will be used for payment verification.</p>
            <div class="p-4 bg-gray-50 rounded-xl border border-gray-100 text-sm text-gray-600 flex items-start gap-3">
              <MapPin class="h-4 w-4 text-gray-400 mt-0.5 shrink-0" />
              <div>
                <p class="font-medium text-gray-900 mb-0.5">Same as delivery address</p>
                <p class="text-xs text-gray-500">Update your addresses in the <NuxtLink to="/account/addresses" class="text-primary hover:underline">Address Book</NuxtLink>.</p>
              </div>
            </div>
          </div>
        </div>

      </div>
    </main>

    <!-- Toast -->
    <Transition name="slide-up">
      <div v-if="toastMsg" class="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 bg-gray-900 text-white px-6 py-3 rounded-full shadow-xl text-sm font-medium flex items-center gap-2">
        <CheckCircle class="h-4 w-4 text-green-400" /> {{ toastMsg }}
      </div>
    </Transition>

    <AppFooter />
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import {
  ArrowLeft, CreditCard, Plus, Lock, AlertCircle, Wallet, Zap, Clock,
  MapPin, Receipt, CheckCircle, Smartphone, Globe
} from '@lucide/vue'

definePageMeta({ middleware: 'auth' })
useHead({ title: 'Payment Methods - Fortress Designs' })

const showAddCard = ref(false)
const selectedCard = ref('card-1')
const toastMsg = ref('')

const newCard = reactive({ holder: '', number: '', expiry: '', cvc: '' })

const demoCards = ref([
  { id: 'card-1', brand: 'Visa', last4: '4242', expiry: '12/27', holder: 'Demo User', isDefault: true },
  { id: 'card-2', brand: 'Mastercard', last4: '5555', expiry: '06/26', holder: 'Demo User', isDefault: false },
])

const wallets = [
  { id: 'apple', name: 'Apple Pay', description: 'Pay with Touch ID or Face ID', icon: Smartphone, color: 'bg-gray-900 text-white' },
  { id: 'google', name: 'Google Pay', description: 'Fast checkout with your Google account', icon: Globe, color: 'bg-blue-500 text-white' },
]

function formatCardNumber(e) {
  let val = e.target.value.replace(/\D/g, '').substring(0, 16)
  newCard.number = val.replace(/(.{4})/g, '$1 ').trim()
}

function addDemoCard() {
  if (!newCard.holder || !newCard.number || !newCard.expiry) {
    showToast('Please fill in all required fields')
    return
  }
  const last4 = newCard.number.replace(/\s/g, '').slice(-4)
  const numberRaw = newCard.number.replace(/\s/g, '')
  const brand = numberRaw.startsWith('4') ? 'Visa' : numberRaw.startsWith('5') ? 'Mastercard' : 'Amex'
  demoCards.value.push({
    id: `card-${Date.now()}`,
    brand,
    last4,
    expiry: newCard.expiry,
    holder: newCard.holder,
    isDefault: false,
  })
  Object.assign(newCard, { holder: '', number: '', expiry: '', cvc: '' })
  showAddCard.value = false
  showToast('Card saved! (Demo mode — not stored)')
}

function showToast(msg) {
  toastMsg.value = msg
  setTimeout(() => (toastMsg.value = ''), 3000)
}
</script>

<style scoped>
.slide-up-enter-active, .slide-up-leave-active { transition: all 0.3s ease; }
.slide-up-enter-from, .slide-up-leave-to { opacity: 0; transform: translateX(-50%) translateY(20px); }
</style>

// client/src/pages/account/payment.tsx
import { useState } from "react";
import { Link } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { 
  ArrowLeft, CreditCard, Plus, Trash2, Check, Shield, Lock, X
} from "lucide-react";
import { useAuth } from "@/lib/auth";
import { useToast } from "@/hooks/use-toast";
import ProtectedRoute from "@/components/ProtectedRoute";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fadeInUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 }
};

interface PaymentMethod {
  id: number;
  type: "visa" | "mastercard" | "amex" | "discover";
  last4: string;
  expMonth: string;
  expYear: string;
  name: string;
  isDefault: boolean;
}

function PaymentMethodsContent() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [showAddForm, setShowAddForm] = useState(false);

  const [paymentMethods, setPaymentMethods] = useState<PaymentMethod[]>([
    {
      id: 1,
      type: "visa",
      last4: "4242",
      expMonth: "12",
      expYear: "2026",
      name: user?.displayName || "John Doe",
      isDefault: true
    },
    {
      id: 2,
      type: "mastercard",
      last4: "8888",
      expMonth: "06",
      expYear: "2025",
      name: user?.displayName || "John Doe",
      isDefault: false
    },
  ]);

  const [newCard, setNewCard] = useState({
    number: "",
    expMonth: "",
    expYear: "",
    cvc: "",
    name: "",
  });

  const handleSetDefault = (id: number) => {
    setPaymentMethods(methods => methods.map(method => ({
      ...method,
      isDefault: method.id === id
    })));
    toast({
      title: "Default payment method updated",
      description: "Your default payment method has been changed.",
    });
  };

  const handleDelete = (id: number) => {
    setPaymentMethods(methods => methods.filter(method => method.id !== id));
    toast({
      title: "Payment method removed",
      description: "The card has been removed from your account.",
    });
  };

  const handleAddCard = (e: React.FormEvent) => {
    e.preventDefault();
    const last4 = newCard.number.slice(-4);
    const type = getCardType(newCard.number);
    const id = Math.max(...paymentMethods.map(m => m.id), 0) + 1;
    
    setPaymentMethods([...paymentMethods, {
      id,
      type: type as "visa" | "mastercard" | "amex" | "discover",
      last4,
      expMonth: newCard.expMonth,
      expYear: newCard.expYear,
      name: newCard.name,
      isDefault: paymentMethods.length === 0
    }]);
    
    setShowAddForm(false);
    setNewCard({ number: "", expMonth: "", expYear: "", cvc: "", name: "" });
    toast({
      title: "Card added",
      description: `Card ending in ${last4} has been added to your account.`,
    });
  };

  const getCardType = (number: string): string => {
    const cleanNumber = number.replace(/\s/g, "");
    if (cleanNumber.startsWith("4")) return "visa";
    if (cleanNumber.startsWith("5")) return "mastercard";
    if (cleanNumber.startsWith("3")) return "amex";
    if (cleanNumber.startsWith("6")) return "discover";
    return "visa";
  };

  const getCardLogo = (type: string) => {
    const colors: Record<string, string> = {
      visa: "from-blue-600 to-blue-800",
      mastercard: "from-red-500 to-orange-500",
      amex: "from-blue-400 to-blue-600",
      discover: "from-orange-500 to-orange-700",
    };
    return colors[type] || colors.visa;
  };

  const formatCardNumber = (value: string) => {
    const cleaned = value.replace(/\D/g, "");
    const chunks = cleaned.match(/.{1,4}/g);
    return chunks ? chunks.join(" ") : cleaned;
  };

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      <Navbar />

      <main className="flex-1 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial="initial"
            animate="animate"
            variants={fadeInUp}
          >
            <div className="mb-8">
              <Link href="/account">
                <Button variant="ghost" size="sm" className="gap-2 mb-4">
                  <ArrowLeft className="h-4 w-4" />
                  Back to Dashboard
                </Button>
              </Link>
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                <div>
                  <h1 className="text-3xl font-bold text-gray-900">Payment Methods</h1>
                  <p className="text-gray-500 mt-1">Manage your saved payment methods</p>
                </div>
                <Button 
                  className="bg-primary text-white gap-2"
                  onClick={() => setShowAddForm(true)}
                >
                  <Plus className="h-4 w-4" />
                  Add Payment Method
                </Button>
              </div>
            </div>

            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 mb-6 flex items-center gap-3">
              <Shield className="h-5 w-5 text-blue-600" />
              <p className="text-sm text-blue-700">
                Your payment information is encrypted and securely stored. We never store your full card number.
              </p>
            </div>

            <AnimatePresence mode="wait">
              {showAddForm && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: "auto" }}
                  exit={{ opacity: 0, height: 0 }}
                  className="mb-6"
                >
                  <Card className="border-0 shadow-sm">
                    <CardHeader className="flex flex-row items-center justify-between">
                      <div>
                        <CardTitle>Add New Card</CardTitle>
                        <CardDescription>Enter your card details below</CardDescription>
                      </div>
                      <Button 
                        variant="ghost" 
                        size="icon"
                        onClick={() => setShowAddForm(false)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </CardHeader>
                    <CardContent>
                      <form onSubmit={handleAddCard} className="space-y-4">
                        <div className="space-y-2">
                          <Label>Card Number</Label>
                          <div className="relative">
                            <CreditCard className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                            <Input
                              placeholder="1234 5678 9012 3456"
                              value={formatCardNumber(newCard.number)}
                              onChange={(e) => setNewCard({ 
                                ...newCard, 
                                number: e.target.value.replace(/\s/g, "").slice(0, 16) 
                              })}
                              className="pl-10"
                              maxLength={19}
                              required
                            />
                          </div>
                        </div>

                        <div className="grid grid-cols-3 gap-4">
                          <div className="space-y-2">
                            <Label>Month</Label>
                            <Input
                              placeholder="MM"
                              value={newCard.expMonth}
                              onChange={(e) => setNewCard({ 
                                ...newCard, 
                                expMonth: e.target.value.slice(0, 2) 
                              })}
                              maxLength={2}
                              required
                            />
                          </div>
                          <div className="space-y-2">
                            <Label>Year</Label>
                            <Input
                              placeholder="YYYY"
                              value={newCard.expYear}
                              onChange={(e) => setNewCard({ 
                                ...newCard, 
                                expYear: e.target.value.slice(0, 4) 
                              })}
                              maxLength={4}
                              required
                            />
                          </div>
                          <div className="space-y-2">
                            <Label>CVC</Label>
                            <div className="relative">
                              <Input
                                placeholder="123"
                                type="password"
                                value={newCard.cvc}
                                onChange={(e) => setNewCard({ 
                                  ...newCard, 
                                  cvc: e.target.value.slice(0, 4) 
                                })}
                                maxLength={4}
                                required
                              />
                              <Lock className="absolute right-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                            </div>
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label>Cardholder Name</Label>
                          <Input
                            placeholder="John Doe"
                            value={newCard.name}
                            onChange={(e) => setNewCard({ ...newCard, name: e.target.value })}
                            required
                          />
                        </div>

                        <div className="flex justify-end gap-2">
                          <Button 
                            type="button" 
                            variant="outline"
                            onClick={() => setShowAddForm(false)}
                          >
                            Cancel
                          </Button>
                          <Button type="submit" className="bg-primary text-white">
                            Add Card
                          </Button>
                        </div>
                      </form>
                    </CardContent>
                  </Card>
                </motion.div>
              )}
            </AnimatePresence>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <AnimatePresence mode="popLayout">
                {paymentMethods.map((method, index) => (
                  <motion.div
                    key={method.id}
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ delay: index * 0.05 }}
                  >
                    <Card className={`border-0 shadow-sm overflow-hidden ${
                      method.isDefault ? 'ring-2 ring-primary' : ''
                    }`}>
                      <div className={`h-32 bg-gradient-to-br ${getCardLogo(method.type)} p-6 relative`}>
                        {method.isDefault && (
                          <div className="absolute top-3 right-3 bg-white/20 backdrop-blur-sm text-white text-xs px-2 py-1 rounded-full">
                            Default
                          </div>
                        )}
                        <div className="absolute bottom-4 left-6 right-6">
                          <p className="text-white/80 text-sm mb-1">Card Number</p>
                          <p className="text-white font-mono text-lg tracking-wider">
                            •••• •••• •••• {method.last4}
                          </p>
                        </div>
                        <CreditCard className="absolute top-4 left-4 h-8 w-8 text-white/40" />
                      </div>
                      <CardContent className="p-4">
                        <div className="flex items-center justify-between mb-3">
                          <div>
                            <p className="font-medium text-gray-900">{method.name}</p>
                            <p className="text-sm text-gray-500">
                              Expires {method.expMonth}/{method.expYear}
                            </p>
                          </div>
                          <span className="text-xs font-semibold text-gray-400 uppercase">
                            {method.type}
                          </span>
                        </div>

                        <div className="flex items-center gap-2">
                          {!method.isDefault && (
                            <Button
                              variant="outline"
                              size="sm"
                              className="gap-1"
                              onClick={() => handleSetDefault(method.id)}
                            >
                              <Check className="h-3 w-3" />
                              Set Default
                            </Button>
                          )}
                          {!method.isDefault && (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="gap-1 text-red-600 hover:text-red-700 hover:bg-red-50"
                              onClick={() => handleDelete(method.id)}
                            >
                              <Trash2 className="h-3 w-3" />
                              Remove
                            </Button>
                          )}
                        </div>
                      </CardContent>
                    </Card>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>

            {paymentMethods.length === 0 && !showAddForm && (
              <Card className="border-0 shadow-sm">
                <CardContent className="p-12 text-center">
                  <CreditCard className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                  <h3 className="text-lg font-medium text-gray-900 mb-2">No payment methods saved</h3>
                  <p className="text-gray-500 mb-4">Add a card to make checkout faster</p>
                  <Button 
                    className="bg-primary text-white"
                    onClick={() => setShowAddForm(true)}
                  >
                    Add Payment Method
                  </Button>
                </CardContent>
              </Card>
            )}

            <Card className="border-0 shadow-sm mt-6">
              <CardHeader>
                <CardTitle className="text-lg">Billing Address</CardTitle>
                <CardDescription>The address associated with your primary payment method</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                  <div className="text-sm text-gray-600">
                    <p className="font-medium text-gray-900">{user?.displayName || 'Customer'}</p>
                    <p>123 Main Street</p>
                    <p>New York, NY 10001</p>
                    <p>United States</p>
                  </div>
                  <Link href="/account/addresses">
                    <Button variant="outline" size="sm">
                      Change
                    </Button>
                  </Link>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}

export default function PaymentMethods() {
  return (
    <ProtectedRoute>
      <PaymentMethodsContent />
    </ProtectedRoute>
  );
}
