// pages/account/profile.vue
<template>
  <div class="min-h-screen flex flex-col bg-gray-50">
    <AppNavbar />

    <main class="flex-1 py-8">
      <div class="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">

        <!-- Back -->
        <NuxtLink to="/account">
          <button class="flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900 mb-6 transition-colors">
            <ArrowLeft class="h-4 w-4" /> Back to Dashboard
          </button>
        </NuxtLink>

        <h1 class="text-3xl font-bold text-gray-900 mb-2">Profile Settings</h1>
        <p class="text-gray-500 mb-8">Manage your personal information and account security.</p>

        <!-- Avatar Card -->
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Profile Photo</h2>
          <div class="flex items-center gap-6">
            <div class="relative shrink-0">
              <div v-if="authStore.user?.photoURL" class="w-24 h-24 rounded-full overflow-hidden ring-4 ring-primary ring-offset-2">
                <img :src="authStore.user.photoURL" :alt="authStore.user.displayName || 'User'" class="w-full h-full object-cover" />
              </div>
              <div v-else class="w-24 h-24 rounded-full bg-gradient-to-br from-primary to-purple-700 flex items-center justify-center ring-4 ring-primary ring-offset-2">
                <span class="text-4xl font-bold text-white">{{ userInitial }}</span>
              </div>
            </div>
            <div>
              <p class="font-medium text-gray-900 text-sm mb-1">{{ authStore.user?.displayName || 'No name set' }}</p>
              <p class="text-sm text-gray-500 mb-3">{{ authStore.user?.email }}</p>
              <div class="flex items-center gap-2">
                <span class="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full"
                  :class="authStore.user?.emailVerified ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'">
                  <CheckCircle v-if="authStore.user?.emailVerified" class="h-3 w-3" />
                  <AlertCircle v-else class="h-3 w-3" />
                  {{ authStore.user?.emailVerified ? 'Verified' : 'Not Verified' }}
                </span>
                <span class="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full bg-purple-100 text-purple-700">
                  <component :is="providerIcon" class="h-3 w-3" />
                  {{ authProviderLabel }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- Edit Name Form -->
        <div class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-4">Personal Information</h2>

          <div v-if="nameSuccess" class="mb-4 p-3 bg-green-50 border border-green-200 text-green-700 rounded-lg text-sm flex items-center gap-2">
            <CheckCircle class="h-4 w-4 shrink-0" /> Display name updated successfully!
          </div>
          <div v-if="nameError" class="mb-4 p-3 bg-red-50 border border-red-200 text-red-700 rounded-lg text-sm flex items-center gap-2">
            <AlertCircle class="h-4 w-4 shrink-0" /> {{ nameError }}
          </div>

          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Display Name</label>
              <div class="relative">
                <User class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  v-model="displayName"
                  type="text"
                  placeholder="Your full name"
                  class="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-sm"
                />
              </div>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
              <div class="relative">
                <Mail class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  :value="authStore.user?.email"
                  type="email"
                  disabled
                  class="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50 text-gray-400 text-sm cursor-not-allowed"
                />
              </div>
              <p class="text-xs text-gray-400 mt-1">Email cannot be changed here. Use account security settings.</p>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Account Created</label>
              <div class="relative">
                <Calendar class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  :value="accountCreated"
                  disabled
                  class="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50 text-gray-400 text-sm cursor-not-allowed"
                />
              </div>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Last Sign In</label>
              <div class="relative">
                <Clock class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
                <input
                  :value="lastSignIn"
                  disabled
                  class="w-full pl-10 pr-4 py-3 border border-gray-200 rounded-xl bg-gray-50 text-gray-400 text-sm cursor-not-allowed"
                />
              </div>
            </div>

            <button
              @click="saveDisplayName"
              :disabled="nameSaving || displayName === authStore.user?.displayName"
              class="flex items-center gap-2 bg-primary hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-6 py-3 rounded-xl font-medium transition-colors text-sm"
            >
              <Loader2 v-if="nameSaving" class="h-4 w-4 animate-spin" />
              <Save v-else class="h-4 w-4" />
              {{ nameSaving ? 'Saving…' : 'Save Changes' }}
            </button>
          </div>
        </div>

        <!-- Change Password -->
        <div v-if="isEmailProvider" class="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
          <h2 class="text-lg font-semibold text-gray-900 mb-1">Change Password</h2>
          <p class="text-sm text-gray-500 mb-4">We'll send a password reset link to your email address.</p>

          <div v-if="passwordMsg" class="mb-4 p-3 rounded-lg text-sm flex items-center gap-2"
            :class="passwordMsg.type === 'success' ? 'bg-green-50 border border-green-200 text-green-700' : 'bg-red-50 border border-red-200 text-red-700'">
            <CheckCircle v-if="passwordMsg.type === 'success'" class="h-4 w-4 shrink-0" />
            <AlertCircle v-else class="h-4 w-4 shrink-0" />
            {{ passwordMsg.text }}
          </div>

          <button
            @click="sendPasswordReset"
            :disabled="passwordSending"
            class="flex items-center gap-2 border-2 border-primary text-primary hover:bg-primary hover:text-white disabled:opacity-50 px-6 py-3 rounded-xl font-medium transition-colors text-sm"
          >
            <Loader2 v-if="passwordSending" class="h-4 w-4 animate-spin" />
            <KeyRound v-else class="h-4 w-4" />
            {{ passwordSending ? 'Sending…' : 'Send Password Reset Email' }}
          </button>
        </div>

        <!-- Danger Zone -->
        <div class="bg-white rounded-2xl shadow-sm border border-red-100 p-6">
          <h2 class="text-lg font-semibold text-red-600 mb-1">Sign Out</h2>
          <p class="text-sm text-gray-500 mb-4">Sign out of your Fortress Designs account on this device.</p>
          <button
            @click="handleLogout"
            class="flex items-center gap-2 border-2 border-red-200 text-red-600 hover:bg-red-50 px-6 py-3 rounded-xl font-medium transition-colors text-sm"
          >
            <LogOut class="h-4 w-4" />
            Sign Out
          </button>
        </div>

      </div>
    </main>

    <AppFooter />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import {
  ArrowLeft, User, Mail, Calendar, Clock, Save, Loader2, CheckCircle, AlertCircle,
  KeyRound, LogOut, Shield, LogIn
} from '@lucide/vue'
import { useAuthStore } from '~/stores/auth'

definePageMeta({ middleware: 'auth' })
useHead({ title: 'Profile Settings - Fortress Designs' })

const authStore = useAuthStore()
const { $firebaseAuth } = useNuxtApp()

// Editable state
const displayName = ref(authStore.user?.displayName || '')
const nameSaving = ref(false)
const nameSuccess = ref(false)
const nameError = ref('')
const passwordSending = ref(false)
const passwordMsg = ref(null)

// Computed info
const userInitial = computed(() => {
  const name = authStore.user?.displayName || authStore.user?.email || '?'
  return name.charAt(0).toUpperCase()
})

const accountCreated = computed(() => {
  const ts = authStore.user?.metadata?.creationTime
  if (!ts) return '—'
  return new Date(ts).toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'long', day: 'numeric' })
})

const lastSignIn = computed(() => {
  const ts = authStore.user?.metadata?.lastSignInTime
  if (!ts) return '—'
  return new Date(ts).toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'long', day: 'numeric' })
})

const authProviderLabel = computed(() => {
  const providers = authStore.user?.providerData?.map(p => p.providerId) || []
  if (providers.includes('google.com')) return 'Google'
  if (providers.includes('password')) return 'Email & Password'
  return 'Unknown'
})

const providerIcon = computed(() => {
  const providers = authStore.user?.providerData?.map(p => p.providerId) || []
  return providers.includes('google.com') ? LogIn : Shield
})

const isEmailProvider = computed(() =>
  authStore.user?.providerData?.some(p => p.providerId === 'password') ?? false
)

// Save display name via Firebase updateProfile
async function saveDisplayName() {
  nameError.value = ''
  nameSuccess.value = false
  nameSaving.value = true
  try {
    await $firebaseAuth.updateDisplayName(displayName.value)
    nameSuccess.value = true
    setTimeout(() => (nameSuccess.value = false), 4000)
  } catch (err) {
    nameError.value = err.message || 'Failed to update name. Please try again.'
  } finally {
    nameSaving.value = false
  }
}

async function sendPasswordReset() {
  passwordSending.value = true
  passwordMsg.value = null
  try {
    await $firebaseAuth.sendPasswordReset(authStore.user?.email)
    passwordMsg.value = { type: 'success', text: 'Password reset email sent! Check your inbox.' }
  } catch (err) {
    passwordMsg.value = { type: 'error', text: err.message || 'Failed to send reset email.' }
  } finally {
    passwordSending.value = false
  }
}

async function handleLogout() {
  await $firebaseAuth.logout()
  navigateTo('/')
}
</script>

// client/src/pages/account/profile.tsx
import { useState } from "react";
import { Link } from "wouter";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { 
  User, Mail, Phone, Camera, ArrowLeft, Save, Bell, Shield, Trash2
} from "lucide-react";
import { useAuth } from "@/lib/auth";
import { useToast } from "@/hooks/use-toast";
import ProtectedRoute from "@/components/ProtectedRoute";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fadeInUp = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 }
};

function ProfileSettingsContent() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [isLoading, setIsLoading] = useState(false);

  const [formData, setFormData] = useState({
    firstName: user?.displayName?.split(' ')[0] || '',
    lastName: user?.displayName?.split(' ').slice(1).join(' ') || '',
    email: user?.email || '',
    phone: '',
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    toast({
      title: "Profile updated",
      description: "Your profile information has been saved successfully.",
    });
    setIsLoading(false);
  };

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      <Navbar />

      <main className="flex-1 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial="initial"
            animate="animate"
            variants={fadeInUp}
          >
            <div className="mb-8">
              <Link href="/account">
                <Button variant="ghost" size="sm" className="gap-2 mb-4">
                  <ArrowLeft className="h-4 w-4" />
                  Back to Dashboard
                </Button>
              </Link>
              <h1 className="text-3xl font-bold text-gray-900">Profile Settings</h1>
              <p className="text-gray-500 mt-1">Manage your personal information and preferences</p>
            </div>

            <div className="space-y-6">
              <Card className="border-0 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <User className="h-5 w-5 text-primary" />
                    Personal Information
                  </CardTitle>
                  <CardDescription>Update your personal details</CardDescription>
                </CardHeader>
                <CardContent>
                  <form onSubmit={handleSubmit} className="space-y-6">
                    <div className="flex items-center gap-6">
                      <div className="relative">
                        <div className="w-24 h-24 rounded-full bg-gradient-to-r from-primary to-secondary flex items-center justify-center text-white text-3xl font-bold">
                          {formData.firstName.charAt(0) || user?.email?.charAt(0).toUpperCase()}
                        </div>
                        <button
                          type="button"
                          className="absolute bottom-0 right-0 w-8 h-8 rounded-full bg-white shadow-md flex items-center justify-center hover:bg-gray-50 transition-colors"
                        >
                          <Camera className="h-4 w-4 text-gray-600" />
                        </button>
                      </div>
                      <div>
                        <h3 className="font-semibold text-gray-900">{user?.displayName || 'User'}</h3>
                        <p className="text-sm text-gray-500">{user?.email}</p>
                        <p className="text-xs text-gray-400 mt-1">Member since {new Date().getFullYear()}</p>
                      </div>
                    </div>

                    <Separator />

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-2">
                        <Label htmlFor="firstName">First Name</Label>
                        <Input
                          id="firstName"
                          value={formData.firstName}
                          onChange={(e) => handleInputChange('firstName', e.target.value)}
                          placeholder="Enter your first name"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="lastName">Last Name</Label>
                        <Input
                          id="lastName"
                          value={formData.lastName}
                          onChange={(e) => handleInputChange('lastName', e.target.value)}
                          placeholder="Enter your last name"
                        />
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <div className="space-y-2">
                        <Label htmlFor="email">Email Address</Label>
                        <div className="relative">
                          <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                          <Input
                            id="email"
                            type="email"
                            value={formData.email}
                            onChange={(e) => handleInputChange('email', e.target.value)}
                            className="pl-10"
                            placeholder="you@example.com"
                          />
                        </div>
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="phone">Phone Number</Label>
                        <div className="relative">
                          <Phone className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
                          <Input
                            id="phone"
                            type="tel"
                            value={formData.phone}
                            onChange={(e) => handleInputChange('phone', e.target.value)}
                            className="pl-10"
                            placeholder="+1 (555) 000-0000"
                          />
                        </div>
                      </div>
                    </div>

                    <div className="flex justify-end">
                      <Button 
                        type="submit" 
                        className="bg-primary text-white gap-2"
                        disabled={isLoading}
                      >
                        <Save className="h-4 w-4" />
                        {isLoading ? "Saving..." : "Save Changes"}
                      </Button>
                    </div>
                  </form>
                </CardContent>
              </Card>

              <Card className="border-0 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Bell className="h-5 w-5 text-primary" />
                    Notification Preferences
                  </CardTitle>
                  <CardDescription>Choose what updates you want to receive</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {[
                      { label: "Order Updates", description: "Receive notifications about your order status" },
                      { label: "Promotional Emails", description: "Get notified about sales and special offers" },
                      { label: "New Arrivals", description: "Be the first to know about new products" },
                    ].map((item, index) => (
                      <div key={index} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                        <div>
                          <p className="font-medium text-gray-900">{item.label}</p>
                          <p className="text-sm text-gray-500">{item.description}</p>
                        </div>
                        <label className="relative inline-flex items-center cursor-pointer">
                          <input type="checkbox" className="sr-only peer" defaultChecked={index === 0} />
                          <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-primary"></div>
                        </label>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              <Card className="border-0 shadow-sm">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Shield className="h-5 w-5 text-primary" />
                    Security
                  </CardTitle>
                  <CardDescription>Manage your account security settings</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                      <div>
                        <p className="font-medium text-gray-900">Change Password</p>
                        <p className="text-sm text-gray-500">Update your password regularly for security</p>
                      </div>
                      <Button variant="outline" size="sm">
                        Update
                      </Button>
                    </div>
                    <div className="flex items-center justify-between p-4 bg-gray-50 rounded-xl">
                      <div>
                        <p className="font-medium text-gray-900">Two-Factor Authentication</p>
                        <p className="text-sm text-gray-500">Add an extra layer of security</p>
                      </div>
                      <Button variant="outline" size="sm">
                        Enable
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>

              <Card className="border-0 shadow-sm border-red-100">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-red-600">
                    <Trash2 className="h-5 w-5" />
                    Danger Zone
                  </CardTitle>
                  <CardDescription>Irreversible actions</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex items-center justify-between p-4 bg-red-50 rounded-xl">
                    <div>
                      <p className="font-medium text-gray-900">Delete Account</p>
                      <p className="text-sm text-gray-500">Permanently delete your account and all data</p>
                    </div>
                    <Button variant="outline" size="sm" className="text-red-600 border-red-200 hover:bg-red-50">
                      Delete Account
                    </Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </motion.div>
        </div>
      </main>

      <Footer />
    </div>
  );
}

export default function ProfileSettings() {
  return (
    <ProtectedRoute>
      <ProfileSettingsContent />
    </ProtectedRoute>
  );
}
